version: '3'

services:
  postgres-brand:
    image: postgres:12.3
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_BRAND_USER}
      POSTGRES_PASSWORD: ${POSTGRES_BRAND_PASSWORD}
      POSTGRES_DB: ${POSTGRES_BRAND_DB}
    volumes:
      - /root/brand/data:/var/lib/postgresql/data
  brand-be:
    image: docker.pkg.github.com/mocchi-app/brand-be/brand-be:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      API_KEY: ${API_KEY}
      API_SECRET_KEY: ${API_SECRET_KEY}
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      DATABASE_URL: postgresql://postgres-brand:5432/${POSTGRES_BRAND_DB}
      JDBC_DATABASE_USERNAME: ${POSTGRES_BRAND_USER}
      JDBC_DATABASE_PASSWORD: ${POSTGRES_BRAND_PASSWORD}
